version: '3.4'

services:
  mysql:
    image: mysql:5
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
  # mysql:
  #   image: mysql:8
  #   ports:
  #     - '3306:3306'
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test