name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run database
        run: docker-compose up -d
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: e2e test monorepo packages
        run: |
          npm run test:e2e -- --filter=@anchan828/typeorm-history
          npm run test:e2e -- --filter=@anchan828/typeorm-transformers
          npm run test:e2e -- --filter=@anchan828/typeorm-decorators
