name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run database
        run: docker-compose up -d
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: e2e test monorepo packages
        run: |
          npm run test:e2e -- --scope=@anchan828/typeorm-history
          npm run test:e2e -- --scope=@anchan828/typeorm-transformers
          npm run test:e2e -- --scope=@anchan828/typeorm-decorators
      - name: Unit test monorepo packages
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
